#  Broadcasting trong NumPy áp dụng cho tất cả các phép toán +, -, *, /, //, %, **, v.v.

# Quy tắc Broadcasting:
- NumPy so sánh shape từ chiều cuối về đầu:

- Hai chiều tương thích nếu:
    + Bằng nhau, HOẶC
    + Một trong hai bằng 1, HOẶC
    + Một trong hai không tồn tại

# Dot và *
- dấu * 
- Phép nhân element-wise (Hadamard product):
- Nhân từng phần tử tương ứng với nhau
- Yêu cầu cùng shape hoặc có thể broadcasting
-
-
- Dot - Phép nhân ma trận (Matrix multiplication):
- Nhân ma trận theo quy tắc đại số tuyến tính
- Shape phải tương thích: (m,n) × (n,p) = (m,p)

In [7]:
import numpy as np

A = np.array([[56, 0, 4.4, 68],
             [1.2, 104, 52, 8],
             [1.8 , 135, 99, 0.9]])
print(A)
print(A.shape)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
(3, 4)


In [ ]:
column = A.sum(axis=0) # sum of column 
print(column) # Array 1 chiều

[ 59.  239.  155.4  76.9]
(4,)


In [ ]:
percentage = 100*A/column.reshape(1,4) # có reshape hay không cũng được   # reshape : đổi thành 1 hàng 4 cột 
# tính % của từng phần tử trong cột dựa theo tổng của cột đó 
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [17]:
B = np.array([[1,2,3],
              [4,5,6]]) #(2x3)
C = np.array([100,200,300]) # (1x3) 
# khi làm phép cộng python sẽ tự biến đổi C thành - chỉ cộng được khi là ma trận 1xn và ma trận có kích thước bằng nó
# nếu cộng 2 ma trận 2x3 và 3x3 thì sẽ không được
# C = [[100,200,300], 
#      [100,200,300]]
print(B+C)

[[101 202 303]
 [104 205 306]]


In [ ]:
D =  np.array([[1,2,3],
              [4,5,6]]) # (2x3) - nếu (3x3) thì không cộng được với (2x1)
E = np.array([[100],
              [200]]) # (2x1) - nó sẽ cộng theo hàng 
F = np.array([[100,300],
              [200,400]])
print(D+E)
#print(D+F) # (2,3) (2,2)  không thể cộng 

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 